# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: ai-ml
  postfix: 0004
  location: southeastasia
  environment: prod
  enable_aml_computecluster: false
  enable_aml_secure_workspace: false



  # Azure DevOps
  ado_service_connection_rg: AZURE-ARM-AML
  ado_service_connection_aml_ws: AZURE-ARM-AML

  # Compute target for pipeline
  training_target: ado-instance-tl01
  training_target_sku: STANDARD_DS11_v2
  training_target_min_nodes: 0
  training_target_max_nodes: 2
  training_target_tier: dedicated


  # DO NOT TOUCH

  # For pipeline reference
  resource_group: tl01-ai-ml
  aml_workspace: aml-tl01-ai-ml

  # For data registration
  storage_account_name: blobtl01iotapp
  storage_account_key: 2aCqM3tiyOdrq8nLRjj4amjqK6ZApOxSRMKVy4E47INNHqdPocIkad88Zgo5Ydmg7xW+X02przYl+ASt+zUSlQ==

  storage_connection_string: DefaultEndpointsProtocol=https;AccountName=blobtl01iotapp;AccountKey=2aCqM3tiyOdrq8nLRjj4amjqK6ZApOxSRMKVy4E47INNHqdPocIkad88Zgo5Ydmg7xW+X02przYl+ASt+zUSlQ==;EndpointSuffix=core.windows.net