$schema: https://azuremlschemas.azureedge.net/latest/batchDeployment.schema.json
name: synchronous-machines-batch-dp
description: Batch deployment for synchronous machines model
endpoint_name: synchronous-machines-batch
model: azureml:synchronous-machines-model@latest
code_configuration:
  code: ../online
  scoring_script: score.py
compute: azureml:cpu-cluster
environment: azureml:synchronous-machines-env@latest
resources:
  instance_count: 1
  instance_type: Standard_DS2_v2
max_concurrency_per_instance: 2
mini_batch_size: 10
output_action: append_row
output_file_name: predictions.csv
retry_settings:
  max_retries: 3
  timeout: 30
error_threshold: 10
logging_level: info
tags:
  environment: production
  owner: data-science-team
  project: synchronous-machines
  version: "1.0"