$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
description: Production deployment for defect machines model
endpoint_name: defect-machines-endpoint
model: azureml:defect-machines-model@latest
# code_configuration:
#   code: .
#   scoring_script: score.py
instance_type: Standard_DS2_v2
instance_count: 1
# scale_settings:
#   min_instances: 1
#   max_instances: 3
#   scale_down_delay_seconds: 600
# resource_requirements:
#   cpu: 1
#   memory_in_gb: 4
data_collector:
  collections:
    model_inputs:
      enabled: 'True'
    model_outputs:
      enabled: 'True'
    model_inputs_outputs:
      enabled: 'True'
tags:
  environment: production
  project: defect-machines
  version: "1.0"