$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: defect-machines-env
version: 7
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
conda_file: ../../../data-science/environment/train-conda.yml
description: Environment created from a Docker image plus a Conda environment file