channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - azureml-mlflow==1.50.0
      - azureml-sdk==1.50.0
      - scikit-learn==0.24.1
      - pandas==1.2.1
      - joblib==1.0.0
      - matplotlib==3.3.3
      - opentelemetry-sdk==1.25.0
      - opentelemetry-api==1.25.0
      - azure-monitor-opentelemetry-exporter==1.0.0b20

