variables:
- template: ../../config-infra-prod.yml

trigger:
- none

pool:
  vmImage: $(ap_vm_image)

stages:

  - stage: ConnectWorkspace
    displayName: Connect Workspace with Resource Group
    jobs:
    - job: ConnectRGandWorkspace
      displayName: Connect Workspace and Resource Group
      steps:
      - checkout: self
        path: s/

      - template: /aml-cli-v2/install-az-cli.yml

      - template: /aml-cli-v2/install-aml-cli.yml

      - template: /aml-cli-v2/connect-to-workspace.yml

      # Step 1: Retrieve Secrets from Azure Key Vault
      - task: AzureKeyVault@2
        displayName: 'Retrieve Secrets from Azure Key Vault'
        inputs:
          azureSubscription: $(ado_service_connection_aml_ws) # Service connection with access to Key Vault
          KeyVaultName: 'kv-tl01-ai-ml'
          SecretsFilter: '*'

      # Step 2: Login with Service Principal using Secrets
      - script: |
          az login --service-principal \
            -u $(servicePrincipalId) \
            -p $(servicePrincipalKey) \
            --tenant $(tenantId)
        displayName: 'Azure Login with Service Principal'