trigger:
  paths:
    include:
    - data-science/*

pool:
  vmImage: ubuntu-20.04

variables:
  # Base URL for data blob storage
  data_base_url: "https://blobtl01aiml.blob.core.windows.net/azureml-blobstore-e48ca893-7fd3-49f5-96c0-1cef93a62a81/TL01"
  # This will be set dynamically by the pipeline
  data_timestamp_path: ""

stages:
  - stage: UnitTest
    displayName: Run Unit Test
    jobs:
    - job: RunUnitTest
      displayName: Run unit tests
      steps:
      - checkout: self
        path: s/
        
      # Generate timestamp in YYYY/MM/dd/HH format for data path
      - bash: |
          # Generate timestamp path in YYYY/MM/dd/HH format (e.g. 2025/03/24/19)
          TIMESTAMP_PATH=$(date '+%Y/%m/%d/%H')
          echo "Generated timestamp path: $TIMESTAMP_PATH"
          
          # Set pipeline variable for use in data registration
          echo "##vso[task.setvariable variable=data_timestamp_path]$TIMESTAMP_PATH"
        displayName: 'Generate Dynamic Timestamp Path'
      
      # Register the data with dynamic path
      - template: /aml-cli-v2/register-data.yml
        parameters:
          data_type: uri_file
          data_name: synchronous-machines-data  # Match name in data.yml
          data_file: mlops/azureml/train/data.yml


